version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.4
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  beta:
    macos:
      xcode: 15.4
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
      - beta:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - develop-test
